FROM ubuntu:14.04
WORKDIR /tmp/
RUN apt-get -y update && apt-get -y upgrade

# XXX might not need all of these packages
RUN apt-get install -y build-essential checkinstall \
	libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev \
	tk-dev libgdbm-dev libc6-dev libbz2-dev \
	wget curl uuid netcat

RUN apt-get install -y python python-dev python-pip
RUN pip install --upgrade pip

copy ./crawler/requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN curl -fsSL https://get.docker.com/ | sh

RUN mkdir /crawler
COPY . /crawler/
WORKDIR /crawler/



# tests are pointing to this directory
RUN ln -s crawler config_and_metrics_crawler

WORKDIR tests
# let's pull an ubuntu image before starting the tests why?
CMD ./test_all.sh
