FROM gliderlabs/alpine:3.3

RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/main libseccomp
RUN apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/community docker

RUN apk add --update \
    python \
    python-dev \
    py-pip \
    build-base \
    linux-headers \
    docker \
  && pip install --upgrade pip \
  && rm -rf /var/cache/apk/*

copy crawler/requirements.txt /requirements.txt
copy tests/requirements.txt /requirements-test.txt
run pip install -r requirements.txt && pip install -r requirements-test.txt

WORKDIR /crawler

COPY . /crawler

CMD ls && pip install . && python -c "import sys; print sys.path" && py.test 
